# Generated by Django 2.1.3 on 2018-12-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username1', models.CharField(max_length=100)),
                ('Username2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interest_Model',
            fields=[
                ('interestid', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(default='', max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=100)),
                ('receiver', models.CharField(max_length=100)),
            ],
        ),
    ]
