# Generated by Django 2.1.2 on 2018-12-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181207_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest_model',
            name='username',
        ),
        migrations.DeleteModel(
            name='Interest_Model',
        ),
    ]
